#!/usr/bin/env bash
# Install nginx web server and return a page that contains
# the string "Holberton School"
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
service nginx start
