#!/usr/bin/env bash
# Redirecting /redirect_me to another site
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/ a rewrite ^/redirect_me https://www.duckduckgo.com permanent;' /etc/nginx/sites-enabled/default
service nginx restart
