#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and
# "I am invincible!!" when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

i="0"

while [ $i ]
do
    echo "To infinity and beyond"
    sleep 2
i=$((i+1))
done
