#!/usr/bin/env bash
# This script displays numbers 1-4, then phrase
# 5-9, then phrase, 10-17, then phrase, 18-20
# while-loop with case statement

i=1

while [ $i -le 20 ]
do
    echo "$i"
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((i++))
done
