#!/usr/bin/env bash
#script configures an Ubuntu server with requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.


#DEFAULT IP FOR LOCALHOST
#LOCAL_IP="127.0.0.1"
#DEFAULT IP FOR FACEBOOK
#FB_IP="157.240.11.35"

#HOSTNAME TO ADD
#HOSTNAMES=/vagrant/Documents/holberton-system_engineering-devops/0x08-networking_basics_2/hosts.new
#PATH TO THE HOSTS FILE
#ETC_HOSTS_FILE=/etc/hosts

function addhosts
{
    #Adding $HOSTNAMES to $ETC_HOSTS_FILE
    cp /etc/hosts ~/hosts.new
    sed -i s/^127.0.0.1/127.0.0.2/ ~/hosts.new
    echo "8.8.8.8facebook.com" >> ~/hosts.new
    cp -f ~/hosts.new /etc/hosts
}

addhosts
