#!/usr/bin/env bash
#script configures an Ubuntu server with requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.


#DEFAULT IP FOR LOCALHOST
#LOCAL_IP="127.0.0.1"
#DEFAULT IP FOR FACEBOOK
#FB_IP="157.240.11.35"

function addhosts
{
    #Adding $HOSTNAMES to $ETC_HOSTS_FILE
    cp /etc/hosts ~/hosts.new
    sed -i s/^127.0.0.1/127.0.0.2/ ~/hosts.new
    echo "facebook.com 8.8.8.8" >> ~/hosts.new
    cp -f ~/hosts.new /etc/hosts
}

addhosts
